[tool.black]
line-length = 79
target-version = ['py39']
exclude = '/venv|/migrations'

[tool.mypy]
check_untyped_defs = true
disallow_any_generics = true
disallow_incomplete_defs = true
disallow_untyped_decorators = true
no_implicit_optional = true
warn_redundant_casts = true
warn_return_any = true
warn_unused_configs = true
warn_unused_ignores = true
exclude = ['migrations/','venv/']
plugins = ["sqlmypy", "pydantic.mypy"]
namespace_packages = true

[tool.pydantic-mypy]
init_forbid_extra = true
init_typed = true
warn_required_dynamic_aliases = true
warn_untyped_fields = true

[tool.isort]
py_version=39
force_grid_wrap = 0
include_trailing_comma = true
line_length = 79
multi_line_output = 3
skip = ["venv","bin","migrations"]
use_parentheses = true