"""fix items backref

Revision ID: 25c331fa3797
Revises: 653b31fb507a
Create Date: 2022-02-13 11:57:38.289810

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '25c331fa3797'
down_revision = '653b31fb507a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('item', sa.Column('items_id', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_item_items_id_items'), 'item', 'items', ['items_id'], ['id'])
    op.drop_constraint('fk_items_item_id_item', 'items', type_='foreignkey')
    op.drop_column('items', 'item_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('items', sa.Column('item_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_items_item_id_item', 'items', 'item', ['item_id'], ['id'])
    op.drop_constraint(op.f('fk_item_items_id_items'), 'item', type_='foreignkey')
    op.drop_column('item', 'items_id')
    # ### end Alembic commands ###
