"""Adding Location and Item states

Revision ID: 5b0b99b8e5c6
Revises: b1c0c3e36a1f
Create Date: 2022-01-30 17:16:08.976349

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5b0b99b8e5c6'
down_revision = 'b1c0c3e36a1f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.drop_column('y_coordinate')
        batch_op.drop_column('x_coordinate')
        batch_op.drop_column('scene')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('game_state', schema=None) as batch_op:
        batch_op.add_column(sa.Column('scene', sa.VARCHAR(), nullable=True))
        batch_op.add_column(sa.Column('x_coordinate', sa.INTEGER(), nullable=True))
        batch_op.add_column(sa.Column('y_coordinate', sa.INTEGER(), nullable=True))

    # ### end Alembic commands ###
