"""Fix one to many multiple join paths

Revision ID: 6b0968883c7b
Revises: 36dc23330424
Create Date: 2022-02-08 21:59:16.835269

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '6b0968883c7b'
down_revision = '36dc23330424'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('fk_adventure_log_discovered_locations_id_location', 'adventure_log', type_='foreignkey')
    op.drop_constraint('fk_adventure_log_discovered_items_id_item', 'adventure_log', type_='foreignkey')
    op.drop_constraint('fk_adventure_log_discoverable_locations_id_location', 'adventure_log', type_='foreignkey')
    op.drop_constraint('fk_adventure_log_discoverable_items_id_item', 'adventure_log', type_='foreignkey')
    op.drop_column('adventure_log', 'discovered_locations_id')
    op.drop_column('adventure_log', 'discovered_items_id')
    op.drop_column('adventure_log', 'discoverable_items_id')
    op.drop_column('adventure_log', 'discoverable_locations_id')
    op.add_column('item', sa.Column('adventure_log_discovered_items', sa.Integer(), nullable=True))
    op.add_column('item', sa.Column('adventure_log_discoverable_items', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_item_adventure_log_discovered_items_adventure_log'), 'item', 'adventure_log', ['adventure_log_discovered_items'], ['id'])
    op.create_foreign_key(op.f('fk_item_adventure_log_discoverable_items_adventure_log'), 'item', 'adventure_log', ['adventure_log_discoverable_items'], ['id'])
    op.add_column('location', sa.Column('adventure_log_discovered_locations', sa.Integer(), nullable=True))
    op.add_column('location', sa.Column('adventure_log_discoverable_locations', sa.Integer(), nullable=True))
    op.create_foreign_key(op.f('fk_location_adventure_log_discovered_locations_adventure_log'), 'location', 'adventure_log', ['adventure_log_discovered_locations'], ['id'])
    op.create_foreign_key(op.f('fk_location_adventure_log_discoverable_locations_adventure_log'), 'location', 'adventure_log', ['adventure_log_discoverable_locations'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_location_adventure_log_discoverable_locations_adventure_log'), 'location', type_='foreignkey')
    op.drop_constraint(op.f('fk_location_adventure_log_discovered_locations_adventure_log'), 'location', type_='foreignkey')
    op.drop_column('location', 'adventure_log_discoverable_locations')
    op.drop_column('location', 'adventure_log_discovered_locations')
    op.drop_constraint(op.f('fk_item_adventure_log_discoverable_items_adventure_log'), 'item', type_='foreignkey')
    op.drop_constraint(op.f('fk_item_adventure_log_discovered_items_adventure_log'), 'item', type_='foreignkey')
    op.drop_column('item', 'adventure_log_discoverable_items')
    op.drop_column('item', 'adventure_log_discovered_items')
    op.add_column('adventure_log', sa.Column('discoverable_locations_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('adventure_log', sa.Column('discoverable_items_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('adventure_log', sa.Column('discovered_items_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.add_column('adventure_log', sa.Column('discovered_locations_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.create_foreign_key('fk_adventure_log_discoverable_items_id_item', 'adventure_log', 'item', ['discoverable_items_id'], ['id'])
    op.create_foreign_key('fk_adventure_log_discoverable_locations_id_location', 'adventure_log', 'location', ['discoverable_locations_id'], ['id'])
    op.create_foreign_key('fk_adventure_log_discovered_items_id_item', 'adventure_log', 'item', ['discovered_items_id'], ['id'])
    op.create_foreign_key('fk_adventure_log_discovered_locations_id_location', 'adventure_log', 'location', ['discovered_locations_id'], ['id'])
    # ### end Alembic commands ###
