"""Inital Game and GameState tables

Revision ID: b1c0c3e36a1f
Revises: 
Create Date: 2022-01-26 23:39:53.081943

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b1c0c3e36a1f'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('game',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_id'), 'game', ['id'], unique=False)
    op.create_table('game_state',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('x_coordinate', sa.Integer(), nullable=True),
    sa.Column('y_coordinate', sa.Integer(), nullable=True),
    sa.Column('health_points', sa.Integer(), nullable=True),
    sa.Column('scene', sa.String(), nullable=True),
    sa.Column('created', sa.DateTime(), nullable=True),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_game_state_id'), 'game_state', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_game_state_id'), table_name='game_state')
    op.drop_table('game_state')
    op.drop_index(op.f('ix_game_id'), table_name='game')
    op.drop_table('game')
    # ### end Alembic commands ###
