"""add map table

Revision ID: bef37b3436a0
Revises: b27c50a16d99
Create Date: 2022-02-02 22:13:13.186390

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'bef37b3436a0'
down_revision = 'b27c50a16d99'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('map',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('game_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['game_id'], ['game.id'], name=op.f('fk_map_game_id_game')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_map'))
    )
    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_map_id'), ['id'], unique=False)

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_inventory_id'), ['id'], unique=False)

    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_location_id'), ['id'], unique=False)
        batch_op.create_foreign_key(batch_op.f('fk_location_map_id_map'), 'map', ['map_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('location', schema=None) as batch_op:
        batch_op.drop_constraint(batch_op.f('fk_location_map_id_map'), type_='foreignkey')
        batch_op.drop_index(batch_op.f('ix_location_id'))

    with op.batch_alter_table('inventory', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_inventory_id'))

    with op.batch_alter_table('map', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_map_id'))

    op.drop_table('map')
    # ### end Alembic commands ###
